In [54]:
import pandas as pd
import numpy as np

In [55]:
df = pd.read_csv("merged_dataset.csv")

In [56]:
df.head()

,Timestamp,PM2.5 (µg/m³),PM10 (µg/m³),NO2 (µg/m³),SO2 (µg/m³),CO (mg/m³),Ozone (µg/m³),AT (°C),RH (%),WS (m/s),WD (deg),Location
0,2025-01-01 00:00:00,57.30,124.43,19.92,5.70,0.50,45.38,23.33,60.83,1.05,130.66,"Prabhat Colony, Jalgaon"
1,2025-01-02 00:00:00,46.42,118.48,28.77,12.93,0.56,42.47,20.77,51.51,1.00,144.38,"Prabhat Colony, Jalgaon"
2,2025-01-03 00:00:00,49.16,132.78,33.29,12.52,0.59,43.54,20.97,44.86,1.03,151.52,"Prabhat Colony, Jalgaon"
3,2025-01-04 00:00:00,53.94,140.37,32.29,10.69,0.69,40.18,21.20,46.32,1.01,161.16,"Prabhat Colony, Jalgaon"
4,2025-01-05 00:00:00,60.32,150.04,70.99,10.20,0.49,39.87,20.77,50.32,0.94,174.74,"Prabhat Colony, Jalgaon"

In [57]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11315 entries, 0 to 11314
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Timestamp      11315 non-null  object
 1   PM2.5 (µg/m³)  11075 non-null  float64
 2   PM10 (µg/m³)   11077 non-null  float64
 3   NO2 (µg/m³)    11050 non-null  float64
 4   SO2 (µg/m³)    11000 non-null  float64
 5   CO (mg/m³)     11085 non-null  float64
 6   Ozone (µg/m³)  11068 non-null  float64
 7   AT (°C)        10927 non-null  float64
 8   RH (%)         10813 non-null  float64
 9   WS (m/s)       10861 non-null  float64
 10  WD (deg)       10851 non-null  float64
 11  Location       11315 non-null  object
dtypes: float64(10), object(2)
memory usage: 1.0+ MB

In [58]:
df.shape

(11315, 12)

In [59]:
df.isnull().sum()

Timestamp          0
PM2.5 (µg/m³)    240
PM10 (µg/m³)     238
NO2 (µg/m³)      265
SO2 (µg/m³)      315
CO (mg/m³)       230
Ozone (µg/m³)    247
AT (°C)          388
RH (%)           502
WS (m/s)         454
WD (deg)         464
Location           0
dtype: int64

In [60]:
(df.isnull().sum()/len(df))*100

Timestamp        0.000000
PM2.5 (µg/m³)    2.121078
PM10 (µg/m³)     2.103403
NO2 (µg/m³)      2.342024
SO2 (µg/m³)      2.783915
CO (mg/m³)       2.032700
Ozone (µg/m³)    2.182943
AT (°C)          3.429076
RH (%)           4.436589
WS (m/s)         4.012373
WD (deg)         4.100751
Location         0.000000
dtype: float64

In [61]:
df.duplicated().sum()

0

In [62]:
df['Timestamp'] = pd.to_datetime(df['Timestamp'])

In [63]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11315 entries, 0 to 11314
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Timestamp      11315 non-null  datetime64[ns]
 1   PM2.5 (µg/m³)  11075 non-null  float64
 2   PM10 (µg/m³)   11077 non-null  float64
 3   NO2 (µg/m³)    11050 non-null  float64
 4   SO2 (µg/m³)    11000 non-null  float64
 5   CO (mg/m³)     11085 non-null  float64
 6   Ozone (µg/m³)  11068 non-null  float64
 7   AT (°C)        10927 non-null  float64
 8   RH (%)         10813 non-null  float64
 9   WS (m/s)       10861 non-null  float64
 10  WD (deg)       10851 non-null  float64
 11  Location       11315 non-null  object
dtypes: datetime64[ns](1), float64(10), object(1)
memory usage: 1.0+ MB

In [64]:
df['Month'] = df['Timestamp'].dt.month
df['Day'] = df['Timestamp'].dt.day
df['DayOfWeek'] = df['Timestamp'].dt.dayofweek

In [65]:
df[['Timestamp','Month','Day']].head()

   Timestamp  Month  Day
0 2025-01-01      1    1
1 2025-01-02      1    2
2 2025-01-03      1    3
3 2025-01-04      1    4
4 2025-01-05      1    5

In [66]:
def get_season(month):

    if month in [12,1,2]:
        return 'Winter'

    elif month in [3,4,5]:
        return 'Summer'

    elif month in [6,7,8,9]:
        return 'Monsoon'

    else:
        return 'PostMonsoon'

df['Season'] = df['Month'].apply(get_season)

In [67]:
df = df.sort_values(
    by=['Location','Timestamp']
)

In [68]:
df.select_dtypes(include=np.number).columns

Index(['PM2.5 (µg/m³)', 'PM10 (µg/m³)', 'NO2 (µg/m³)', 'SO2 (µg/m³)',
       'CO (mg/m³)', 'Ozone (µg/m³)', 'AT (°C)', 'RH (%)', 'WS (m/s)',
       'WD (deg)', 'Month', 'Day', 'DayOfWeek'],
      dtype='object')

In [69]:
numeric_cols = df.select_dtypes(include='number').columns

In [70]:
df[numeric_cols] = (
    df.groupby('Location')[numeric_cols]
      .transform(lambda x: x.interpolate())
)

In [71]:
df.isnull().sum()

Timestamp        0
PM2.5 (µg/m³)    0
PM10 (µg/m³)     0
NO2 (µg/m³)      0
SO2 (µg/m³)      0
CO (mg/m³)       0
Ozone (µg/m³)    0
AT (°C)          0
RH (%)           0
WS (m/s)         0
WD (deg)         0
Location         0
Month            0
Day              0
DayOfWeek        0
Season           0
dtype: int64

In [72]:
(df.isnull().sum()/len(df))*100

Timestamp        0.0
PM2.5 (µg/m³)    0.0
PM10 (µg/m³)     0.0
NO2 (µg/m³)      0.0
SO2 (µg/m³)      0.0
CO (mg/m³)       0.0
Ozone (µg/m³)    0.0
AT (°C)          0.0
RH (%)           0.0
WS (m/s)         0.0
WD (deg)         0.0
Location         0.0
Month            0.0
Day              0.0
DayOfWeek        0.0
Season           0.0
dtype: float64

In [73]:
df[numeric_cols] = (
    df.groupby('Location')[numeric_cols]
      .transform(lambda x: x.fillna(x.median()))
)

In [74]:
df.isnull().sum()

Timestamp        0
PM2.5 (µg/m³)    0
PM10 (µg/m³)     0
NO2 (µg/m³)      0
SO2 (µg/m³)      0
CO (mg/m³)       0
Ozone (µg/m³)    0
AT (°C)          0
RH (%)           0
WS (m/s)         0
WD (deg)         0
Location         0
Month            0
Day              0
DayOfWeek        0
Season           0
dtype: int64

In [75]:
df['PM2.5 (µg/m³)'].describe()

count    11315.000000
mean        37.826430
std         21.370969
min          1.590000
25%         20.590000
50%         34.040000
75%         51.800000
max        174.150000
Name: PM2.5 (µg/m³), dtype: float64

In [76]:
cols = [
    'PM2.5 (µg/m³)',
    'PM10 (µg/m³)',
    'NO2 (µg/m³)',
    'SO2 (µg/m³)',
    'CO (mg/m³)',
    'Ozone (µg/m³)'
]

In [77]:
for col in cols:

    lower = df[col].quantile(0.01)
    upper = df[col].quantile(0.99)

    df[col] = df[col].clip(lower, upper)

In [78]:
df['Dispersion'] = (
    df['WS (m/s)'] *
    df['AT (°C)']
)

In [79]:
df.to_csv(
    "cleaned_aqi_dataset.csv",
    index=False
)

In [27]:
clean_df = pd.read_csv(
    "cleaned_aqi_dataset.csv"
)

clean_df.head()

,Timestamp,PM2.5 (µg/m³),PM10 (µg/m³),NO2 (µg/m³),SO2 (µg/m³),CO (mg/m³),Ozone (µg/m³),AT (°C),RH (%),WS (m/s),WD (deg),Location,Month,Day,DayOfWeek,Season,Dispersion
0,2025-01-01,78.05,164.160,60.0900,3.28,0.71,26.07,27.29,64.42,0.41,134.71,"Bandra Kurla Complex, Mumbai",1,1,2,Winter,11.1889
1,2025-01-02,66.10,158.300,65.1000,3.23,0.76,27.09,27.19,63.48,0.36,138.06,"Bandra Kurla Complex, Mumbai",1,2,3,Winter,9.7884
2,2025-01-03,62.84,160.800,65.6456,4.94,0.81,27.98,27.73,61.35,0.29,114.85,"Bandra Kurla Complex, Mumbai",1,3,4,Winter,8.0417
3,2025-01-04,74.26,201.816,65.6456,6.30,1.02,36.71,26.51,63.84,0.39,136.37,"Bandra Kurla Complex, Mumbai",1,4,5,Winter,10.3389
4,2025-01-05,90.18,201.816,65.6456,7.25,0.92,51.21,25.98,67.11,0.24,149.94,"Bandra Kurla Complex, Mumbai",1,5,6,Winter,6.2352